version: 2.1

commands:
  build-kernel-module:
    description: "Builds Kernel Module"
    parameters:
      build-args:
        type: string
        default: "-j`nproc`"
      NV_VERBOSE:
        type: string
        default: "0"
      DEBUG:
        type: string
        default: "0"
    steps:
      - checkout
      - run:
          name: Compile Kernel Module
          command: make modules << parameters.build-args >> NV_VERBOSE=<< parameters.NV_VERBOSE >> DEBUG=<< parameters.DEBUG >>
      - store_artifacts:
          path: test-results


executors:
  arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

  amd64:
    machine:
      image: ubuntu-2004:current
    resource_class: medium


jobs:
  build:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - build-kernel-module:
          build-args: "-j`nproc`"

workflows:
  multi-arch-build:
    jobs:
      - build:
          name: "Building << matrix.architecture >> Kernel Module"
          matrix:
            parameters:
              architecture: ["arm64", "amd64"]